name: redstone_mapper_pg
version: 0.1.1
author: Luiz Mineo <luiz.mineo@gmail.com>
description: PostgreSQL extension for redstone_mapper
homepage: http://redstonedart.org
environment:
  sdk: '>=1.4.0 <2.0.0'
dependencies:
  redstone: '>=0.5.4 < 0.6.0'
  redstone_mapper: '>=0.1.0 < 0.2.0'
  postgresql:
    git:
      git@github.com:dart-targets/dart_postgresql.git
dev_dependencies:
  unittest: '>=0.10.0 <0.12.0'
  mock: '>=0.11.0+1 <0.12.0'
